### ISSUE TITLE
Error in rule read_length_histogram

### ISSUE THREAD

**Issue by ayeletperes** [NBISweden/IgDiscover#106]
Hey,

I've been running IgDiscover (version 0.12) with light chain data, however, the run fails each time in this rule read_length_histogram.

I have used different datasets and still get the same error. Also tried to change the number of threads, but that didn't help either. 

read_length_histogram:
WARNING: QApplication was not created in the main() thread.
terminate called without an active exception
/bin/sh: line 9: 256081 Aborted                 (core dumped) /.conda/envs/igdiscover/bin/python -m snakemake stats/readlengths.pdf --snakefile /.conda/envs/igdiscover/lib/python3.6/site-packages/igdiscover/Snakefile --force -j64 --keep-target-files --keep-remote --attempt 1 --force-use-threads --wrapper-prefix None --latency-wait 3 -p --allowed-rules read_length_histogram --notemp --quiet --no-hooks --nolock --mode 1

**Comment by marcelm** [comment]
This looks very unusual. I’m wondering whether the QApplication warning has something to do with the problem or whether that is inpedendent.

- Are you running this on macOS or Linux?
- Do you have a graphical user interface available?
- Were any other PDF or PNG plots created successfully before the crash occurred?

I’m guessing the problem has something to do with plotting. Plotting is done by `matplotlib`, and the QApplication warning points to Qt (QApplication is the name of one of the components of Qt). Matplotlib does have a Qt backend, but IgDiscover is supposed to not use it at all, so that is the strange part.

Do you have a matplotlib configuration file named `~/.config/matplotlib/matplotlibrc`?

Is your DISPLAY environment variable set? (Find out with `echo $DISPLAY`. If it prints something, it is set.) If so, try to run IgDiscover with this command:
```
DISPLAY= igdiscover run ...
```
(where `...` are the options you would normally use).

**Comment by ayeletperes** [comment]
I'm running on a linux server with a graphical user. It seems that the
problem was with the DISPLAY variable.
Your solution worked. Added the DISPLAY variable before the run.
Thanks!

**Comment by marcelm** [comment]
Great, glad I could help! I’ll try to find the actual cause of the problem – after all, it should work even when the `DISPLAY` variable is set.
