### ISSUE TITLE
length of CDR1 region is not divisible by three

### ISSUE THREAD

**Issue by williamdlees** [NBISweden/IgDiscover#113]
Hi, I see these two warnings:

```
WARNING: Length 26 of CDR1 region in 'IGHV2-S4508*01' is not divisible by three; region info for this gene will not be available
WARNING: Length 23 of CDR1 region in 'IGHV2-S9949*01' is not divisible by three; region info for this gene will not be available
```

Can you please advise me what I can do about them? As I am not giving IgDiscover a gapped V-gene file, I assume it must be working out the CDR region for itself. Have I missed something? I can provide an .ndm and a .aux file for IgBLAST if there is a way to get IgDisvoer to use them.

thanks!

William

**Comment by marcelm** [comment]
Before running IgBLAST against the query sequences, IgDiscover runs IgBLAST on the V gene sequences alone in order to find where the FR1/2/3, CDR1/2 regions are located. That is, it delegates finding these regions to IgBLAST.

I believe the `.aux` file only contains information about the J genes, so that wouldn’t help here. (Also, IgDiscover forces IgBLAST to use an empty `.aux` file anyway.)

IgBLAST will honor the `$IGDATA` environment variable, which you can use to point to your own version of the data directory containing the `internal_data/` directory with the necessary `.ndm.imgt` files. If you need a template, use the directory located at `...your-conda-installation-location/envs/igdiscover/share/igblast/` assuming your IgDiscover environment is named `igdiscover`. Be aware IGDATA needs to point to the directory *containing* the `internal_data/` directory, not the `internal_data/` directory itself.

The reason the length of the CDR1 regions are not divisible by three is probably that IgDiscover predicted a too short V sequence in a previous iteration, so another, probably easier way to solve the problem is to manually edit the `iteration-xx/database/V.fasta` file and add one (or two if needed) made-up nucleotides in the beginning of the problematic sequences. 

IgDiscover should really not predict too short V sequences that it then trips over like this in the next iteration, but that is another issue.

**Comment by williamdlees** [comment]
Thanks, this is very helpful. In this case the short sequences were mine, not IgDiscover's.

**Comment by marcelm** [comment]
Ah great!
