### ISSUE TITLE
error about Microsoft Visual C++ on installation

### ISSUE THREAD

**Issue by zenonisole** [NBISweden/IgDiscover#115]
Hi,

I get an error on installation and I was wondering whether you could help me please?

It asks for Microsoft Visual C++ 14.0 or greater, but I actually have greater than 14.0. I have tried to re-install Microsoft Visual C++ but this did not help. Please would you be able to assist me with this? Screenshot is attached.

Thanks

![screenshot](https://user-images.githubusercontent.com/88020570/128042102-44a12880-5f2a-49a3-92c2-0366055f073b.PNG)

**Comment by marcelm** [comment]
Unfortunately, we don’t support running IgDiscover on Windows. You did not say it, but is it correct that you tried to install IgDiscover using `pip`, that is, running something like `pip install igdiscover`? That will unfortunately not be enough because `pip` can only install Python dependencies, whereas IgDiscover depends on some non-Python programs as well, in particular IgBLAST, PEAR, FLASH and MUSCLE. So even if you install MS Visual C++ properly, you won’t be able to run IgDiscover.

I suggest that you either use a Linux machine somewhere or install Windows Subsystem for Linux (WSL). Then you can follow our regular installation instructions using Conda, which will properly install all dependencies.
